### ISSUE TITLE
How to run this example?

### ISSUE THREAD

**Issue by croepke** [BreckoEC/share-extension-expo-example#2]
First of all: Thanks for creating this plugin! 

I followed your instructions, but get the following error: 

Error: Cannot find native module 'ShareExtensionNative', js engine: hermes
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:102:17 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:148:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:39 in handleError
at node_modules/expo/build/errors/ExpoErrorManager.js:25:19 in errorHandler
at node_modules/expo/build/errors/ExpoErrorManager.js:30:24 in <anonymous>
at node_modules/@react-native/polyfills/error-guard.js:49:36 in ErrorUtils.reportFatalError
at node_modules/metro-config/node_modules/metro-runtime/src/polyfills/require.js:225:40 in guardedLoadModule
at node_modules/metro-config/node_modules/metro-runtime/src/polyfills/require.js:127:23 in metroRequire
at http://192.168.178.124:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&strict=false&minify=false:null in global

After cloning the repo I just did a "npm install" and then a "npx expo start" and tried to run expo app on the iOS simulator and my own phone. 

Since you wrote "Run the expo app and open it once (to setup the api entry into the keychain)" I assumed this was the correct way to do it. 

Am I doing something wrong?

**Comment by geetee24** [comment]
the documentation leaves MUCH unanswered and needs to be updated to use EAS

**Comment by Remeic** [comment]
Hi @croepke 
Have you tried the following steps?

- Clone
- npm i
- npx expo prebuild --no-install
- npx expo run:ios
